version: '3.8'

services:
  # lyskills app (PHP-FPM)
  app:
    env_file:
      - .env  # This loads variables from .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lyskills-app
    volumes:
      - .:/home/nomilyskills/public_html
    networks:
      - lyskills-network
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  # MySQL database
  db:
    image: mysql:5.7
    container_name: lyskills-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - lyskills-network
    ports:
      - 3306:3306

  # Nginx for reverse proxy
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8080:8080
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/home/nomilyskills/public_html
    depends_on:
      - app
    networks:
      - lyskills-network

networks:
  lyskills-network:
    driver: bridge
