<?php 


return [
    'home' => 'Lyskills in an online educational platform where instructors can upload their video content and can target their student locally and globally. Students can get online training about any topic in any language with life time access of thousands of our video courses.Learn online courses and build creative business skills to achieve your personal and professional goals.',
    'default' => 'Lyskills in an online educational platform where instructors can upload their video content and can target their student locally and globally. Students can get online training about any topic in any language with life time access of thousands of our video courses.Learn online courses and build creative business skills to achieve your personal and professional goals.',
    'engineering' => 'Enroll in online engineering courses or explore in specific areas such as electrical engineering, automation, mechanical engineering, embedded-systems, raspberry-pi and many more of engineering field.',
    'it' => 'Learn online IT Courses from Lyskils. Instructors from every region of the world can upload their video courses and start training of their student locally and globally in IT training courses with E certificate.',
    'mathematics' => 'Learn your mathematics training online by different and expert instructors of the world. Student can learn online training of mathematics including geometry, calculus, mathematical method, algebra and many more in mathematical field.',
    'designing' => 'Learn online designing courses from E commerce platform lyskills. Students and get their online training of designing, like interior , fashion, graphic and  web designing and all about designing field from instructors in different languages.',
    'photography' => 'Learn online digital photography training from a global platform Lyskills, learn your digital photography online training courses with E certificate from globally expert instructors in all ranked languages.',
    'contact_us' => 'Lyskills is an online learning platform where instructors can upload their video contact and students can get life time access to all our courses in different languages. You can get your skills with Lyskills from distance learning platform.',
    'privacy' => 'Privacy Policy of Lyskills will take care the Instructor Online courses , Instructor Video Content , rights of Student who buy online Courses from Lyskills.',
    'terms' => 'Our all users including our instructors and students should follow our terms and conditions of our online learning platform Lyskills.',
    'about_us' => 'Lyskills is an online learning platform where instructors can upload their multiple video contact and students can get life time access to all our courses in different languages. You can get your skills with Lyskills, a distance learning platform. Instructor can teach their students locally and globally and can get their life time business',
    'posts' => 'Lyskills is a Platform where student and instructors come from globally for enhancing their skills. so our Blog will help the Instructor, Student as well as user for improving his Skills',
    'accounting_and_finance' => 'Learn financial accounting online courses from Lyskills. Finance instructor can upload their video courses on E learning platform, students can get their online training of financial accounting and build a foundation of core business skills in finance and accounting.',
];