<?php

$site_settings = [
        "s3Url" => env('AWS_URL'),
        "no_reply_email_pass" => env('NO_REPLY_EMAIL_PASS'),
        "max_tble_size" => 9_0000000,
        "retry_time" => 5,
        "show_site_log" => true,
        "login_profile" => true,
        "guest_search_bar" => true,
        "category_menu" => true,
        "homepage_image" => true,
        "show_courses_main_page" => true,
        "main_courses_heading" => false,
        "all_categories" => true,
        "all_posts" => true,
        "all_faqs" => true,
        "all_faqs" => true,
        "aos_js" => false,
        "aos_css" => false,
        "guest_footer" => true,
        "guest_header" => true,
        "show_courses_on_category" => true,
        "guest_blade" => "layouts.guest_user",
        "welcome_blade" => "welcome",
        "show_blade" => "category.show",
        "guest_blade" => "layouts.guest",
        "guest_blade" => "layouts.guest",
        "user_notification" => true,
        "course_banner" => true,
        "show_course_blade" => "course.show-course",
        "course_nav" => true,
        "course_enrollment_count" => true,
        "course_desc_wishlist_btn" => true,
        "course_desc_share_btn" => true,
        "course_desc_gift_btn" => false,
        "show_course_video" => true,
        "show_hide_coupon" => true,
        "show_hide_course_content" => true,
        "show_hide_course_desc" => true,
        "dir_path" => "storage/img",
        "show_errors_label" => "show_errors",
        "db_helper" => config('database.laravel_db') . ".",
        "err_msg" => "Something went wrong",
        "logout_msg" => 'You are logged out',
        "enable_course_unenroll" => true,
        "admin_guest_search_bar" => true,
        "admin_email" => "anime@bypass.com",
        "coupon_form" => true,
        "store_img_s3" => true,
        "set_time_limit" => 60000,
        "upload_max_filesize" => '2000M',
        "memory_limit" => '8096M',
        "base_env" => env("BASE_ENV"),
        "env_files" => [
                '.env',
                '.env.dev',
                '.env.live.example',
                '.env.dev.example',
        ],
        "en_showing_vid_val" => false
];

return $site_settings;
