<?php
    return [
        "s3Url" => "https://lyskills-by-nouman.s3.ap-southeast-1.amazonaws.com/",
        "show_site_log" => true,
        "login_profile" => true,
        "guest_search_bar" => true,
        "category_menu" => true,
        "homepage_image" => true,
        "show_courses_main_page" => true,
        "main_courses_heading" => false,
        "all_categories" => true,
        "all_posts" => true,
        "all_faqs" => true,
        "all_faqs" => true,
        "aos_js" => false,
        "guest_footer" => true,
        "guest_header" => true,
        "show_courses_on_category" => true,
        "guest_blade" => "layouts.guest_user",
        "welcome_blade" => "welcome",
        "show_blade" => "category.show",
        "guest_blade" => "layouts.guest",
    ];