name: deployment piplines

on:
  push:
    branches: [ "master" ]
jobs:
  laravel-deployment:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.4'
        ftp-server: ${{secrets.FTP_SERVER}}
        ftp-username: ${{secrets.FTP_USERNAME}}
        ftp-password: ${{secrets.FTP_PASS}}
    - uses: actions/checkout@v3

    # - name: Copy .env
    #   run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    # - name: clear cache
    #   run: php artisan config:cache

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    # - name: db connection
    #   env:
    #     DB_CONNECTION: ${{secrets.DB_CONNECTION}}
    #     DB_PASSWORD: ${{secrets.DB_PASSWORD}}
    #     DB_PORT: ${{secrets.DB_PORT}}
    #     DB_DATABASE: ${{secrets.DB_DATABASE}}
    #     DB_USERNAME: ${{secrets.DB_USERNAME}}
    #     DB_HOST: ${{secrets.DB_HOST}}
    #   run: |
    #     php artisan key:generate
    #     php artisan migrate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: npm dependecies
      run: npm install && npm run prod

    # - name: config routing
    #   run: php artisan config:route
